#!/usr/bin/node

/*
	Apache commands
	
    RewriteCond %{REQUEST_URI} !^/js/
    RewriteCond %{REQUEST_URI} !^/css/ 
    RewriteCond %{REQUEST_URI} !^/img/
    RewriteCond %{REQUEST_URI} !^/locales/
    RewriteCond %{REQUEST_URI} !^/config\.js$
    RewriteCond %{REQUEST_URI} !^/favicon\.ico$
    RewriteCond %{REQUEST_URI} !^(.*)\.html$
    RewriteRule ^(.*)$ /index.html*/

var express = require('express');
var fs = require('fs');
var app = express();

var mdir = __dirname + '/..'

app.use('/js', express.static(mdir + '/js'));
app.use('/css', express.static(mdir + '/css'));
app.use('/img', express.static(mdir + '/img'));
app.use('/locales', express.static(mdir + '/locales'));
app.use('/templates', express.static(mdir + '/templates'));
app.get('/config.js', function(req, res) {
    fs.readFile(mdir + '/config.js', 'utf8', function(error, file) {
        res.contentType('application/javascript');
        res.send(file);
    });
});
app.get('*', function(req, res) {
    fs.readFile(mdir + '/index.html', 'utf8', function(error, file) {
        res.send(file);
    });
});

app.listen(3000);

console.log(__dirname + "dev server started");
