#!/usr/bin/node

/*
	Apache commands
	
    RewriteCond %{REQUEST_URI} !^/js/
    RewriteCond %{REQUEST_URI} !^/css/ 
    RewriteCond %{REQUEST_URI} !^/img/
    RewriteCond %{REQUEST_URI} !^/locales/
    RewriteCond %{REQUEST_URI} !^/config\.js$
    RewriteCond %{REQUEST_URI} !^/favicon\.ico$
    RewriteCond %{REQUEST_URI} !^(.*)\.html$
    RewriteRule ^(.*)$ /index.html*/

var express = require('express');
var fs = require('fs');
var app = express();

var mdir = __dirname + '/..'

function staticFile(fileName, mimeType) {
    return function(req, res) {
        fs.readFile(mdir + fileName, 'utf8', function(error, file) {
            if (mimeType)
                res.contentType(mimeType);
            res.send(file);
        });
    };
};

app.use('/js', express.static(mdir + '/js'));
app.use('/css', express.static(mdir + '/css'));
app.use('/img', express.static(mdir + '/img'));
app.use('/locales', express.static(mdir + '/locales'));
app.use('/templates', express.static(mdir + '/templates'));
app.get('/config.js', staticFile('/config.js', 'application/javascript'));
app.get('*', staticFile('/index.html'));

app.listen(3000);

console.log(__dirname + "dev server started");
